secret: secret
server:
  port: 9001
  shutdown: graceful
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: user
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/users?serverTimeznoe=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info,env,caches,beans